### ISSUE TITLE
No default export?

### ISSUE THREAD

**Issue by aleclarson** [ksxnodemodules/static-type-assert#2]
Without `"allowSyntheticDefaultImports": true`, I'm forced to use `require`.

```ts
// Module '"static-type-assert/index"' has no default export. ts(1192)
import assert from "static-type-assert"

// Have to use this instead 😢
import assert = require("static-type-assert")
```

Can we change `export = assert` to `export default assert`?

**Comment by KSXGitHub** [comment]
Would this be a breaking change?

**Comment by aleclarson** [comment]
I'm not sure. I decided to release my own lib: https://github.com/aleclarson/spec.ts

**Comment by KSXGitHub** [comment]
> I'm not sure. I decided to release my own lib: https://github.com/aleclarson/spec.ts

Then I guess I don't have to comply to this issue any longer.

BTW, I like the fact that you use pnpm.
